name = "Edrobot Minecraft Mod Pack"
author = "Edrobot"
version = ".5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c6d2d2d360e5eaea9d5ca6ae4056c73ef789e82482b54cd0f1cc91e0e0e66f"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
