name = "Edrobot ' S Modified Cobblemon Lite"
author = "Edrobot"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e30953d8f1addbf497122ff9a9d58de68313b05752c45df6bca3d09613997091"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
