name = "Edrobot Minecraft Mod Pack"
author = "Edrobot"
version = ".5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "353b5802e5138b536b9cb1bcc02e61c213c832c0cca7d029b10ae945cc031f10"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
