name = "Edrobot Minecraft Mod Pack"
author = "Edrobot"
version = ".5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ecf08637549ce87c4298bc1f7fb324fcc20f32f158fec8015e7d9d88a2c19b0"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
