name = "Edrobot Minecraft Mod Pack"
author = "Edrobot"
version = ".5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9297fbf30861d55ca163050035f9a5ce65a7abf15b21a55dc52e5703171754a3"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
